version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "otter-test-func-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xy92aleibra"
s3_prefix = "otter-test-func-stack"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
